project/models/base.py
from sqlalchemy import Column, Integer
from sqlalchemy.ext.declarative import declared_attr, declarative_base

from .engine import engine


class Base:
    @declared_attr
    def __tablename__(self):
        return f"{self.__name__.lower()}s"

    id = Column(Integer, primary_key=True)


Base = declarative_base(cls=Base, bind=engine)

project/views/auth.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from flask_login import login_user, logout_user

from forms.auth import LoginForm, RegistrationForm
from models.user import User
from models.db import Session

auth_app = Blueprint("auth_app", __name__)


@auth_app.route("/login/", methods=["GET", "POST"], endpoint="login")
def login():
    form = LoginForm()
    if request.method == "POST" and form.validate():
        user = Session.query(User).filter_by(username=form.username.data).first()
        login_user(user)
        return redirect(url_for("main"))
    return render_template("auth/login.html", form=form)


@auth_app.route("/registration", methods=["GET", "POST"], endpoint="registration")
def registration():
    form = RegistrationForm()
    if request.method == "POST" and form.validate():
        user = User(
            username=form.username.data,
            password=form.password.data
        )
        Session.add(user)
        Session.commit()

        flash(
            message=f'Пользователь {user.username} успешно зарегистрирован',
            category='success'
        )
        return redirect(url_for("auth_app.login"))
    return render_template("auth/registration.html", form=form)


@auth_app.route("/logout/", endpoint="logout")
def logout():
    logout_user()
    return redirect(url_for("main"))

project/views/users.py
from flask import Blueprint, render_template

from models.user import User
from models.db import Session

users_app = Blueprint("users_app", __name__)


@users_app.route("/<string:username>/profile/", endpoint="profile")
def profile(username):
    user = Session.query(User).filter_by(username=username).first()
    return render_template("users/profile.html", user=user)

project/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/buttons.css') }}">
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="background"></div>

    {% block navbar %}{% endblock %}

    {% block body %}{% endblock %}

    {% block js %}{% endblock %}
</body>
</html>

project/templates/index.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/posts.css') }}">
{% endblock %}

{% block title %}
    Автоблог - Все посты
{% endblock %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block body %}
    <main class="posts-container">
        <div class="posts">
            {% for post in posts %}
                <div class="post">
                    <div class="post__header">
                        {{ post.title }}
                        {% if current_user == post.user %}
                            <a href="{{ url_for('posts_app.update', post_id=post.id) }}" class="edit-btn">Редактировать</a>
                        {% endif %}
                    </div>
                    <div class="post__body">
                        <div class="post__image">
                            {% if post.image_url %}
                                <img src="{{ post.image_url }}" alt="">
                            {% else %}
                                <img src="{{ url_for('static', filename='car-icon-md.png') }}" alt="">
                            {% endif %}
                        </div>
                        <div class="post__text">
                            {{ post.text[:500] }}...
                            <a href="{{ url_for('posts_app.post', post_id=post.id) }}">Читать полностью</a>
                        </div>
                    </div>
                    <div class="post__footer">
                        <span>Добавлено пользователем {{ post.user.username }}, {{ post.created.strftime('%d.%m.%Y %H:%M') }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>
{% endblock %}

project/templates/navbar.html
<div class="navbar-wrapper">
    <nav class="navbar">
        <a href="{{ url_for('main') }}" class="navbar__logo">
            <img src="{{ url_for('static', filename='img/logo.png') }}" alt="">
        </a>

        <div class="navbar-auth">
            {% if not current_user.is_authenticated %}
                <a href="{{ url_for('auth_app.login') }}">Вход</a>
                <a href="{{ url_for('auth_app.registration') }}">Регистрация</a>
            {% else %}
                <a href="{{ url_for('posts_app.create') }}">Добавить пост</a>
                <a href="{{ url_for('users_app.profile', username=current_user.username) }}">Профиль</a>
                <a href="{{ url_for('auth_app.logout') }}">Выход</a>
            {% endif %}
        </div>
    </nav>
</div>